### ISSUE TITLE
Power cycle doesn't turn on the node if it's off

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/obmd#19] opened 2018-05-09 17:57 UTC
```
[izhmash@moc-haas-deploy ~]$ ipmitool -I lanplus -H 10.10.0.41 -U admin -P password chassis power cycle
Set Chassis Power Control to Cycle failed: Command not supported in present state
```
So this command failed when sent through OBMd and should have triggered [this line](https://github.com/CCI-MOC/obmd/blob/master/internal/driver/ipmi/ipmi.go#L152) to send it a power on but it looks like it didn't since the node was still off.

This was tested with a super-micro server. I'll test it with some other kind of node later.

**Comment by zenhack** [comment] 2018-05-09 21:14
Can you confirm that:

* If you run the cycle/reset command when the node is still off, it returns non-zero as expected?
* It works with the old HIL based code?
* That line is actually not being reached (put a print statement there to check?)

**Comment by Izhmash** [comment] 2018-05-16 18:03
@zenhack I gave it a try and confirmed (through prints) that even when ipmitool is returning `Set Chassis Power Control to Cycle failed: Command not supported in present state`, the error from `err = s.info.ipmitool("chassis", "power", op).Run()` is nil.

Looks like `Run()` might not be understanding that an error occurred here.

**Comment by Izhmash** [comment] 2018-05-16 18:17
I discovered that the output of the command `s.info.ipmitool("chassis", "power", op)` is actually `Chassis Power Control: Reset`, which is different from the error that appears when running ipmitool directly.

**Comment by Izhmash** [comment] 2018-05-16 18:26
Ah I see the issue here, if we do ipmitool cycle rather than reset, then the error should get across to Go.

**Comment by zenhack** [comment] 2018-05-16 20:20
Making power-on an explicit operation seems like a good idea.

**Comment by zenhack** [comment] 2018-05-29 20:35
Now that #20 is merged, we can close this.

**Closed by zenhack** 2018-05-29 20:35 UTC
